<?xml version="1.0"?>
<package format="3">
  <name>orbslam3_core</name>
  <version>1.0.0</version>
  <description>ORB-SLAM3 core library.</description>
  <maintainer email="ldh9501@todo.todo">ldh9501</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
