const $=s=>document.querySelector(s), worker=new Worker('worker.js');let currentRun,runEpoch=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(location.protocol==='file:')$('#notice').innerHTML='<span class="warn">v2 동적 분석은 localhost 서버가 필요합니다. 기존 legacy report만 file://로 여세요.</span>';
async function json(url){const r=await fetch(url);const x=await r.json();if(!r.ok)throw Error(x.error||r.statusText);return x}
async function start(){try{const data=await json('/api/runs');$('#notice').textContent=data.analysis_enabled?'PEM 모델 준비됨 · live SAM-6D와 GPU를 동시에 사용하면 지연이 증가합니다.':'탐색 전용 모드 — 동적 분석 비활성';
 $('#runs').innerHTML=data.runs.map(r=>`<button class="run" data-name="${esc(r.name)}"><b>${esc(r.name)}</b> <span class="badge">${r.kind}</span><br><small>${esc(r.reason||'')}</small></button>`).join('')||'<p>표시할 run이 없습니다.</p>';
 document.querySelectorAll('.run').forEach(b=>b.onclick=()=>openRun(b.dataset.name))}catch(e){if(location.protocol!=='file:')$('#notice').textContent=e.message}}
async function openRun(name){currentRun=name;const epoch=++runEpoch,d=await json(`/api/run/${encodeURIComponent(name)}`);if(epoch!==runEpoch)return;$('#summary').innerHTML=`<h2>${esc(name)} <span class="badge">${d.kind}</span></h2><p>${esc(d.reason||'')}</p>`;
 if(d.kind==='legacy'){$('#summary').innerHTML+=`<p><a href="${d.url}" target="legacy">기존 정적 report 열기</a></p>`;return}
 if(d.kind==='partial'){$('#attempts').innerHTML=`<h3>최종 pose ${d.detections.length}건</h3>`+d.detections.map(x=>`<div class="row">#${x.frame_seq??'—'} ${esc(x.object)} · t_mm ${esc(JSON.stringify(x.t_mm||[]))}</div>`).join('');return}
 if(d.kind!=='explorer_v2')return;$('#attempts').innerHTML=d.attempts.map(a=>`<div class="row attempt" data-id="${a.attempt_id}">#${a.frame_seq} ${esc(a.object)} · ${a.candidate_count} candidates ${a.accepted?'PASS':'REJECT '+esc(a.rejection_reason||'')}</div>`).join('');
 document.querySelectorAll('.attempt').forEach(x=>x.onclick=()=>openAttempt(+x.dataset.id))}
async function openAttempt(id){const run=currentRun,epoch=runEpoch,d=await json(`/api/run/${encodeURIComponent(run)}/candidates?attempt=${id}`);if(epoch!==runEpoch||run!==currentRun)return;$('#candidates').innerHTML=d.candidates.map(c=>`<div class="row candidate" data-attempt="${id}" data-index="${c.index300}">#${c.rank_geo} geo=${Number(c.geometry).toFixed(4)} mask=${Number(c.mask_iou).toFixed(3)} texture=${Number(c.texture).toFixed(3)}</div>`).join('');
 document.querySelectorAll('.candidate').forEach(x=>x.onclick=()=>analyze(+x.dataset.attempt,+x.dataset.index))}
async function analyze(attempt,index){const run=currentRun,epoch=runEpoch;$('#scores').textContent='계산 중…';try{const d=await json(`/api/run/${encodeURIComponent(run)}/analysis?attempt=${attempt}&candidate=${index}`);if(epoch!==runEpoch||run!==currentRun)return;$('#scores').textContent=JSON.stringify({stored:d.stored,recomputed:d.recomputed,absolute_error:d.absolute_error,provenance_mismatch:d.provenance_mismatch,provenance_mismatch_assets:d.provenance_mismatch_assets},null,2);const t=d.timing_summary,fmt=(k)=>t[k]?`${k} p50 ${t[k].p50_ms.toFixed(1)} / p90 ${t[k].p90_ms.toFixed(1)} ms (${t[k].samples})`:'';$('#timing').textContent=`이번 ${d.timing_ms.toFixed(1)} ms · ${fmt('cold')} ${fmt('warm')}`;worker.postMessage(d)}catch(e){if(epoch===runEpoch&&run===currentRun)$('#scores').textContent=e.message}}
worker.onmessage=e=>Object.entries(e.data).forEach(([id,p])=>{const c=$(`#${id}`);c.width=p.w;c.height=p.h;c.getContext('2d').putImageData(new ImageData(p.rgba,p.w,p.h),0,0)});start();
