#!/usr/bin/env python3
"""Run ORB-SLAM3 over the IMU comparison set and normalise outputs.

Conditions (all via the same build, same bag rate):
  1. three_labs_imu      : new bag, IMU-RGBD  (use_imu=true,  imu settings yaml)
  2. three_labs_rgbd     : new bag, RGB-D     (use_imu=false, rgbd settings yaml)   [IMU ablation]
  3. SLAM_three_laps     : RGB-D
  4. SLAM_one_lap        : RGB-D

Must run inside `conda activate orbslam3` with install/setup.bash sourced.
"""
from __future__ import annotations

import os
import shutil
import signal
import subprocess
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ORB_WS = PROJECT_ROOT / "orbslam_ws"
DATA_ROOT = PROJECT_ROOT / "data_slam" / "no_program"
CONFIG_DIR = ORB_WS / "scripts" / "configs"
OUTPUT_BASE = ORB_WS / "output" / "imu_compare"
SETTINGS_RGBD = ORB_WS / "data" / "orbslam3_d455f_640x480_rgbd.yaml"
SETTINGS_IMU = ORB_WS / "data" / "orbslam3_d455f_640x480_rgbd_imu.yaml"

BAG_RATE = float(os.environ.get("ORB_BAG_RATE", "0.5"))
START_DELAY = 12.0
TIMEOUT_SEC = 1800

# (name, bag_dir, use_imu, settings)
CONDITIONS = [
    ("three_labs_imu",  DATA_ROOT / "SLAM_three_labs_rgbd_imu" / "bag", True,  SETTINGS_IMU),
    ("three_labs_rgbd", DATA_ROOT / "SLAM_three_labs_rgbd_imu" / "bag", False, SETTINGS_RGBD),
    ("SLAM_three_laps", DATA_ROOT / "SLAM_three_laps",                  False, SETTINGS_RGBD),
    ("SLAM_one_lap",    DATA_ROOT / "SLAM_one_lap",                     False, SETTINGS_RGBD),
]


def write_config(name, bag_dir, use_imu, settings) -> Path:
    out_dir = OUTPUT_BASE / name
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    cfg_path = CONFIG_DIR / f"imu_compare_{name}.yaml"
    cfg = f"""# auto-generated by run_imu_compare.py
dataset: {name}
bag:
  path: {bag_dir}
  play: true
  clock: true
  rate: {BAG_RATE}
  start_delay: {START_DELAY}
orbslam3:
  settings_path: {settings}
topics:
  rgb: /camera/camera/color/image_raw
  depth: /camera/camera/aligned_depth_to_color/image_raw
  imu: /camera/camera/imu
frames:
  world: map
  camera: camera_color_optical_frame
runtime:
  use_imu: {str(use_imu).lower()}
  save_map_points_on_shutdown: true
dense_map:
  enabled: true
  save_pcd: true
  pcd_output_path: orbslam3_dense_map.pcd
output:
  dir: {out_dir}
  map_points_path: orbslam3_map_points.pcd
visualization:
  enabled: false
"""
    cfg_path.write_text(cfg, encoding="utf-8")
    return cfg_path


def clean_outputs(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for fn in ["CameraTrajectory.txt", "KeyFrameTrajectory.txt",
               "orbslam3_map_points.pcd", "orbslam3_dense_map.pcd",
               "trajectory.txt", "keyframes.txt", "map_points.pcd",
               "orbslam3_launch.log"]:
        p = out_dir / fn
        if p.is_file():
            p.unlink()


def count_lines(p: Path) -> int:
    try:
        with p.open("r", errors="replace") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def run_one(name, bag_dir, use_imu, settings) -> dict:
    cfg = write_config(name, bag_dir, use_imu, settings)
    out_dir = OUTPUT_BASE / name
    clean_outputs(out_dir)
    log_path = out_dir / "orbslam3_launch.log"
    cmd = ["ros2", "launch", "orbslam3_ros2", "orb_slam.launch.py", f"config:={cfg}"]
    t0 = time.time()
    with log_path.open("wb") as log:
        proc = subprocess.Popen(cmd, cwd=str(ORB_WS), stdout=log,
                                stderr=subprocess.STDOUT, preexec_fn=os.setsid)
        try:
            rc = proc.wait(timeout=TIMEOUT_SEC)
        except subprocess.TimeoutExpired:
            os.killpg(os.getpgid(proc.pid), signal.SIGINT)
            try:
                rc = proc.wait(timeout=60)
            except subprocess.TimeoutExpired:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                rc = proc.wait()
    elapsed = time.time() - t0
    for src, dst in [("CameraTrajectory.txt", "trajectory.txt"),
                     ("KeyFrameTrajectory.txt", "keyframes.txt"),
                     ("orbslam3_map_points.pcd", "map_points.pcd")]:
        s = out_dir / src
        if s.exists() and s.stat().st_size > 0:
            shutil.copyfile(s, out_dir / dst)
    return {"name": name, "use_imu": use_imu, "rc": rc, "elapsed_sec": round(elapsed, 1),
            "traj_rows": count_lines(out_dir / "trajectory.txt"),
            "kf_rows": count_lines(out_dir / "keyframes.txt")}


def main() -> int:
    import sys
    targets = [a for a in sys.argv[1:] if not a.startswith("-")]
    results = []
    for cond in CONDITIONS:
        if targets and cond[0] not in targets:
            continue
        print(f"=== {cond[0]} (use_imu={cond[2]}) ===", flush=True)
        r = run_one(*cond)
        print(f"    rc={r['rc']} elapsed={r['elapsed_sec']}s traj={r['traj_rows']} kf={r['kf_rows']}",
              flush=True)
        results.append(r)
    print("\n=== summary ===")
    for r in results:
        ok = r["traj_rows"] > 1 and r["kf_rows"] > 1
        print(f"- [{'PASS' if ok else 'FAIL'}] {r['name']} imu={r['use_imu']} "
              f"traj={r['traj_rows']} kf={r['kf_rows']} rc={r['rc']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
