#!/usr/bin/env python3
"""Run ORB-SLAM3 RGB-D on the four data_slam bags and normalise outputs.

Must run inside `conda activate orbslam3` with the workspace install sourced
(`source orbslam_ws/install/setup.bash`). The launch file auto-plays each bag,
sends SIGINT to the node on bag exit (which saves trajectory + map), and then
shuts the launch down on node exit. We just invoke the launch per dataset and
wait for it to self-terminate, then normalise the file names the spec wants.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]   # .../CLI_environment
ORB_WS = PROJECT_ROOT / "orbslam_ws"
DATA_ROOT = PROJECT_ROOT / "data_slam" / "no_program"
SETTINGS = ORB_WS / "data" / "orbslam3_d455f_640x480_rgbd.yaml"
CONFIG_DIR = ORB_WS / "scripts" / "configs"

DATASETS = [
    "SLAM_forward_backward_repeat",
    "SLAM_one_lap",
    "SLAM_one_lap_back_and_forth",
    "SLAM_three_laps",
]

# Per-dataset hard wall-clock timeout (sec). Bags are ~35-130s; at rate 0.5 plus
# vocab load + start_delay + shutdown, this is a generous safety net only.
TIMEOUT_SEC = 1200
BAG_RATE = float(os.environ.get("ORB_BAG_RATE", "0.5"))   # 1.0 = real-time
START_DELAY = 12.0
# output base: output/<subdir>/<dataset> (subdir empty -> output/<dataset>)
OUTPUT_BASE = ORB_WS / "output" / os.environ.get("ORB_OUTPUT_SUBDIR", "")
DENSE_ENABLED = "false" if os.environ.get("ORB_DISABLE_DENSE") else "true"


def write_config(name: str) -> Path:
    bag_dir = DATA_ROOT / name
    out_dir = OUTPUT_BASE / name
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    cfg_path = CONFIG_DIR / f"{name}.yaml"
    cfg = f"""# auto-generated by run_orbslam_four_bags.py
dataset: {name}
bag:
  path: {bag_dir}
  play: true
  clock: true
  rate: {BAG_RATE}
  start_delay: {START_DELAY}
orbslam3:
  settings_path: {SETTINGS}
topics:
  rgb: /camera/camera/color/image_raw
  depth: /camera/camera/aligned_depth_to_color/image_raw
frames:
  world: map
  camera: camera_color_optical_frame
runtime:
  save_map_points_on_shutdown: true
dense_map:
  enabled: {DENSE_ENABLED}
  save_pcd: {DENSE_ENABLED}
  pcd_output_path: orbslam3_dense_map.pcd
output:
  dir: {out_dir}
  map_points_path: orbslam3_map_points.pcd
visualization:
  enabled: false
"""
    cfg_path.write_text(cfg, encoding="utf-8")
    return cfg_path


def clean_outputs(out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for fn in [
        "CameraTrajectory.txt", "KeyFrameTrajectory.txt",
        "orbslam3_map_points.pcd", "orbslam3_dense_map.pcd",
        "trajectory.txt", "keyframes.txt", "map_points.pcd",
        "orbslam3_launch.log",
    ]:
        p = out_dir / fn
        if p.is_file():
            p.unlink()


def run_dataset(name: str) -> dict:
    cfg = write_config(name)
    out_dir = OUTPUT_BASE / name
    clean_outputs(out_dir)
    launch_cmd = [
        "ros2", "launch", "orbslam3_ros2", "orb_slam.launch.py",
        f"config:={cfg}",
    ]
    log_path = out_dir / "orbslam3_launch.log"
    t0 = time.time()
    with log_path.open("wb") as log:
        proc = subprocess.Popen(
            launch_cmd, cwd=str(ORB_WS), stdout=log,
            stderr=subprocess.STDOUT, preexec_fn=os.setsid,
        )
        try:
            rc = proc.wait(timeout=TIMEOUT_SEC)
        except subprocess.TimeoutExpired:
            import signal
            os.killpg(os.getpgid(proc.pid), signal.SIGINT)
            try:
                rc = proc.wait(timeout=60)
            except subprocess.TimeoutExpired:
                os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                rc = proc.wait()
    elapsed = time.time() - t0

    # Normalise to spec file names
    norm = {
        "CameraTrajectory.txt": "trajectory.txt",
        "KeyFrameTrajectory.txt": "keyframes.txt",
        "orbslam3_map_points.pcd": "map_points.pcd",
    }
    produced = {}
    for src, dst in norm.items():
        s = out_dir / src
        if s.exists() and s.stat().st_size > 0:
            shutil.copyfile(s, out_dir / dst)
            produced[dst] = count_lines(out_dir / dst)
        else:
            produced[dst] = 0
    return {
        "name": name, "launch_rc": rc, "elapsed_sec": round(elapsed, 1),
        "trajectory_rows": produced.get("trajectory.txt", 0),
        "keyframe_rows": produced.get("keyframes.txt", 0),
        "map_pcd_lines": produced.get("map_points.pcd", 0),
        "output": str(out_dir),
    }


def count_lines(p: Path) -> int:
    try:
        with p.open("r", errors="replace") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def main() -> int:
    import sys
    targets = [a for a in sys.argv[1:] if not a.startswith("-")] or DATASETS
    results = []
    for name in targets:
        print(f"=== ORB-SLAM3: {name} ===", flush=True)
        r = run_dataset(name)
        print(f"    rc={r['launch_rc']} elapsed={r['elapsed_sec']}s "
              f"traj_rows={r['trajectory_rows']} kf_rows={r['keyframe_rows']} "
              f"map_lines={r['map_pcd_lines']}", flush=True)
        results.append(r)
    print("\n=== ORB-SLAM3 summary ===")
    all_ok = True
    for r in results:
        # keyframes collapsing to <=1 means tracking never really initialised,
        # even if CameraTrajectory has many (identity) rows -> treat as failure
        ok = r["trajectory_rows"] > 1 and r["keyframe_rows"] > 1
        all_ok = all_ok and ok
        print(f"- [{'PASS' if ok else 'FAIL'}] {r['name']}: rc={r['launch_rc']} "
              f"traj={r['trajectory_rows']} kf={r['keyframe_rows']} "
              f"map_pcd_lines={r['map_pcd_lines']} -> {r['output']}")
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
