import gorilla
import argparse
import os
import sys
from PIL import Image
import os.path as osp
import numpy as np
import random
import importlib
import json

import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
import torchvision.transforms as transforms
import cv2

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, '..', 'Pose_Estimation_Model')
sys.path.append(os.path.join(ROOT_DIR, 'provider'))
sys.path.append(os.path.join(ROOT_DIR, 'utils'))
sys.path.append(os.path.join(ROOT_DIR, 'model'))
sys.path.append(os.path.join(BASE_DIR, 'model', 'pointnet2'))


def get_parser():
    parser = argparse.ArgumentParser(
        description="Pose Estimation")
    # pem
    parser.add_argument("--gpus",
                        type=str,
                        default="0",
                        help="path to pretrain model")
    parser.add_argument("--model",
                        type=str,
                        default="pose_estimation_model",
                        help="path to model file")
    parser.add_argument("--config",
                        type=str,
                        default="config/base.yaml",
                        help="path to config file, different config.yaml use different config")
    parser.add_argument("--iter",
                        type=int,
                        default=600000,
                        help="epoch num. for testing")
    parser.add_argument("--exp_id",
                        type=int,
                        default=0,
                        help="")
    
    # input
    parser.add_argument("--output_dir", nargs="?", help="Path to root directory of the output")
    parser.add_argument("--cad_path", nargs="?", help="Path to CAD(mm)")
    parser.add_argument("--rgb_path", nargs="?", help="Path to RGB image")
    parser.add_argument("--depth_path", nargs="?", help="Path to Depth image(mm)")
    parser.add_argument("--cam_path", nargs="?", help="Path to camera information")
    parser.add_argument("--seg_path", nargs="?", help="Path to segmentation information(generated by ISM)")
    parser.add_argument("--det_score_thresh", default=0.2, type=float, help="The score threshold of detection")
    parser.add_argument("--template_dir", default=None, help="Path to template directory (default: output_dir/templates)")
    args_cfg = parser.parse_args()

    return args_cfg

def init():
    args = get_parser()
    exp_name = args.model + '_' + \
        osp.splitext(args.config.split("/")[-1])[0] + '_id' + str(args.exp_id)
    log_dir = osp.join("log", exp_name)

    cfg = gorilla.Config.fromfile(args.config)
    cfg.exp_name = exp_name
    cfg.gpus     = args.gpus
    cfg.model_name = args.model
    cfg.log_dir  = log_dir
    cfg.test_iter = args.iter

    cfg.output_dir = args.output_dir
    cfg.cad_path = args.cad_path
    cfg.rgb_path = args.rgb_path
    cfg.depth_path = args.depth_path
    cfg.cam_path = args.cam_path
    cfg.seg_path = args.seg_path

    cfg.det_score_thresh = args.det_score_thresh
    cfg.template_dir = args.template_dir
    gorilla.utils.set_cuda_visible_devices(gpu_ids = cfg.gpus)

    return  cfg



from data_utils import (
    load_im,
    get_bbox,
    get_point_cloud_from_depth,
    get_resize_rgb_choose,
)
from draw_utils import draw_detections
import pycocotools.mask as cocomask
import trimesh

rgb_transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                                    std=[0.229, 0.224, 0.225])])

def visualize(rgb, pred_rot, pred_trans, model_points, K, save_path):
    img = draw_detections(rgb, pred_rot, pred_trans, model_points, K, color=(255, 0, 0))
    img = Image.fromarray(np.uint8(img))
    img.save(save_path)
    prediction = Image.open(save_path)
    
    # concat side by side in PIL
    rgb = Image.fromarray(np.uint8(rgb))
    img = np.array(img)
    concat = Image.new('RGB', (img.shape[1] + prediction.size[0], img.shape[0]))
    concat.paste(rgb, (0, 0))
    concat.paste(prediction, (img.shape[1], 0))
    return concat


def _get_template(path, cfg, tem_index=1):
    rgb_path = os.path.join(path, 'rgb_'+str(tem_index)+'.png')
    mask_path = os.path.join(path, 'mask_'+str(tem_index)+'.png')
    xyz_path = os.path.join(path, 'xyz_'+str(tem_index)+'.npy')

    rgb = load_im(rgb_path).astype(np.uint8)
    xyz = np.load(xyz_path).astype(np.float32) / 1000.0  
    mask = load_im(mask_path).astype(np.uint8) == 255

    bbox = get_bbox(mask)
    y1, y2, x1, x2 = bbox
    mask = mask[y1:y2, x1:x2]

    rgb = rgb[:,:,::-1][y1:y2, x1:x2, :]
    if cfg.rgb_mask_flag:
        rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)

    rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
    rgb = rgb_transform(np.array(rgb))

    choose = (mask>0).astype(np.float32).flatten().nonzero()[0]
    if len(choose) <= cfg.n_sample_template_point:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point)
    else:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point, replace=False)
    choose = choose[choose_idx]
    xyz = xyz[y1:y2, x1:x2, :].reshape((-1, 3))[choose, :]

    rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)
    return rgb, rgb_choose, xyz


def get_templates(path, cfg):
    n_template_view = cfg.n_template_view
    all_tem = []
    all_tem_choose = []
    all_tem_pts = []

    total_nView = 42
    for v in range(n_template_view):
        i = int(total_nView / n_template_view * v)
        tem, tem_choose, tem_pts = _get_template(path, cfg, i)
        all_tem.append(torch.FloatTensor(tem).unsqueeze(0).to(DEVICE))
        all_tem_choose.append(torch.IntTensor(tem_choose).long().unsqueeze(0).to(DEVICE))
        all_tem_pts.append(torch.FloatTensor(tem_pts).unsqueeze(0).to(DEVICE))
    return all_tem, all_tem_pts, all_tem_choose


def prepare_frame(rgb, depth, K, depth_scale=1.0):
    """프레임 한 장에서 '객체와 무관한 부분'만 미리 만든다.

    RGB 디코드, 깊이 스케일링, 전체 포인트클라우드 생성은 그 프레임에 객체가 몇 개
    있든 한 번만 하면 되는 일이다. 객체마다 get_test_data 를 부르면 이 셋이 객체
    수만큼 되풀이된다(640x480 에서 객체당 약 26 ms). 그래서 따로 뺐다.

    rgb   : RGB 순서 uint8 (H,W,3) 또는 (H,W)
    depth : 원본 단위(mm) 배열
    """
    whole_image = np.asarray(rgb).astype(np.uint8)
    if len(whole_image.shape)==2:
        whole_image = np.concatenate([whole_image[:,:,None], whole_image[:,:,None], whole_image[:,:,None]], axis=2)
    whole_depth = np.asarray(depth).astype(np.float32) * depth_scale / 1000.0
    K = np.asarray(K, dtype=np.float64).reshape(3, 3)
    return {'image': whole_image, 'depth': whole_depth,
            'pts': get_point_cloud_from_depth(whole_depth, K), 'K': K}


def get_instance_data(frame, cad_path, dets, det_score_thresh, cfg):
    """준비된 프레임(prepare_frame 결과)에서 인스턴스별 PEM 입력을 만든다.

    det 은 파일에서 읽은 dict 그대로도 되고, 메모리의 마스크를 실어 보내도 된다
    ({'score': .., 'mask': bool ndarray}). 후자면 RLE 인코딩/디코딩을 건너뛴다.

    det 마다 'cad' 를 실으면 서로 다른 객체를 한 번에 담을 수 있다(그때 cad_path 는
    쓰이지 않는다). 이 경우 모델점 표본추출이 det 루프 안으로 들어가는데, 순서가
    '객체별로 따로 부를 때'와 같아지도록 루프 맨 앞에 둔다 — 그래야 두 방식이
    같은 난수를 같은 순서로 쓰고 결과가 비교 가능하다.

    반환: (입력 dict, 모델점(det 별 cad 면 리스트), 실제로 쓰인 det 목록)
    """
    whole_image, whole_depth, whole_pts, K = frame['image'], frame['depth'], frame['pts'], frame['K']

    per_det_cad = any(inst.get('cad') is not None for inst in dets)
    if not per_det_cad:
        mesh = trimesh.load_mesh(cad_path)
        model_points = mesh.sample(cfg.n_sample_model_point).astype(np.float32) / 1000.0
        radius = np.max(np.linalg.norm(model_points, axis=1))


    all_model = []
    all_rgb = []
    all_cloud = []
    all_rgb_choose = []
    all_shape_mask = []
    all_crop_bbox = []
    all_score = []
    all_dets = []
    for inst in dets:
        if per_det_cad:
            mesh = trimesh.load_mesh(inst['cad'])
            model_points = mesh.sample(cfg.n_sample_model_point).astype(np.float32) / 1000.0
            radius = np.max(np.linalg.norm(model_points, axis=1))
        score = inst['score']
        if score <= det_score_thresh:
            continue

        # mask — 메모리의 마스크를 그대로 받으면 RLE 왕복을 건너뛴다
        if inst.get('mask') is not None:
            mask = np.asarray(inst['mask'])
        else:
            seg = inst['segmentation']
            h,w = seg['size']
            try:
                rle = cocomask.frPyObjects(seg, h, w)
            except:
                rle = seg
            mask = cocomask.decode(rle)
        mask = np.logical_and(mask > 0, whole_depth > 0)
        if np.sum(mask) > 32:
            bbox = get_bbox(mask)
            y1, y2, x1, x2 = bbox
        else:
            continue
        mask = mask[y1:y2, x1:x2]
        choose = mask.astype(np.float32).flatten().nonzero()[0]

        # pts
        cloud = whole_pts[y1:y2, x1:x2, :].reshape(-1, 3)[choose, :]
        center = np.mean(cloud, axis=0)
        tmp_cloud = cloud - center[None, :]
        flag = np.linalg.norm(tmp_cloud, axis=1) < radius * 1.2
        # A SAM mask can include a thin strip of background depth.  Its mean then
        # moves outside the actual object and the radius gate rejects every point.
        # Median-centre fallback is only used when the legacy mean gate would
        # reject the instance, so already-valid PEM inputs remain byte-for-byte
        # on the old path.
        if np.sum(flag) < 4:
            robust_center = np.median(cloud, axis=0)
            robust_flag = np.linalg.norm(cloud - robust_center[None, :], axis=1) < radius * 1.2
            if np.sum(robust_flag) > np.sum(flag):
                flag = robust_flag
        if np.sum(flag) < 4:
            continue
        choose = choose[flag]
        cloud = cloud[flag]

        # 독립 후보 검증용 입력 실루엣. PEM이 실제로 받아들인 depth-valid/radius-inlier
        # 점만 남기며, 후보 투영과 같은 224 crop 좌표계에서 비교한다. 이후 2048점
        # 표본화 전 mask를 보존해야 입력 크기와 IoU가 난수 표본 밀도에 좌우되지 않는다.
        shape_mask = np.zeros(mask.size, dtype=np.uint8)
        shape_mask[choose] = 1
        shape_mask = shape_mask.reshape(mask.shape)
        shape_mask = cv2.resize(
            shape_mask, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_NEAREST
        ) > 0
        all_shape_mask.append(torch.from_numpy(shape_mask))
        all_crop_bbox.append(torch.tensor([y1, y2, x1, x2], dtype=torch.float32))

        if len(choose) <= cfg.n_sample_observed_point:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point)
        else:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point, replace=False)
        choose = choose[choose_idx]
        cloud = cloud[choose_idx]

        # rgb
        rgb = whole_image.copy()[y1:y2, x1:x2, :][:,:,::-1]
        if cfg.rgb_mask_flag:
            rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)
        rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
        rgb = rgb_transform(np.array(rgb))
        rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)

        all_rgb.append(torch.FloatTensor(rgb))
        all_cloud.append(torch.FloatTensor(cloud))
        all_rgb_choose.append(torch.IntTensor(rgb_choose).long())
        all_score.append(score)
        all_dets.append(inst)
        all_model.append(model_points)

    ret_dict = {}
    if not all_cloud:
        raise ValueError(
            "no valid PEM instances after depth/radius filtering "
            "(requires >32 valid-depth mask pixels and >=4 radius inliers)"
        )
    ret_dict['pts'] = torch.stack(all_cloud).to(DEVICE)
    ret_dict['rgb'] = torch.stack(all_rgb).to(DEVICE)
    ret_dict['rgb_choose'] = torch.stack(all_rgb_choose).to(DEVICE)
    ret_dict['shape_mask'] = torch.stack(all_shape_mask).to(DEVICE)
    ret_dict['crop_bbox_yxyx'] = torch.stack(all_crop_bbox).to(DEVICE)
    ret_dict['score'] = torch.FloatTensor(all_score).to(DEVICE)

    ninstance = ret_dict['pts'].size(0)
    if per_det_cad:
        ret_dict['model'] = torch.stack([torch.FloatTensor(m) for m in all_model]).to(DEVICE)
    else:
        ret_dict['model'] = torch.FloatTensor(model_points).unsqueeze(0).repeat(ninstance, 1, 1).to(DEVICE)
    ret_dict['K'] = torch.FloatTensor(K).unsqueeze(0).repeat(ninstance, 1, 1).to(DEVICE)
    return ret_dict, (all_model if per_det_cad else model_points), all_dets


def get_test_data(rgb_path, depth_path, cam_path, cad_path, seg_path, det_score_thresh, cfg):
    """파일 경로로 받는 기존 진입점 — 동작은 예전과 같다(위 두 함수로 나뉘었을 뿐)."""
    with open(seg_path) as f:
        dets = json.load(f) # keys: scene_id, image_id, category_id, bbox, score, segmentation

    cam_info = json.load(open(cam_path))
    frame = prepare_frame(load_im(rgb_path), load_im(depth_path),
                          np.array(cam_info['cam_K']).reshape(3, 3), cam_info['depth_scale'])

    ret_dict, model_points, all_dets = get_instance_data(
        frame, cad_path, dets, det_score_thresh, cfg)
    return ret_dict, frame['image'], frame['pts'].reshape(-1, 3), model_points, all_dets



if __name__ == "__main__":
    cfg = init()

    random.seed(cfg.rd_seed)
    torch.manual_seed(cfg.rd_seed)

    # model
    print("=> creating model ...")
    MODEL = importlib.import_module(cfg.model_name)
    model = MODEL.Net(cfg.model)
    model = model.to(DEVICE)
    model.eval()
    checkpoint = os.path.join(os.path.dirname((os.path.abspath(__file__))), 'checkpoints', 'sam-6d-pem-base.pth')
    gorilla.solver.load_checkpoint(model=model, filename=checkpoint)

    print("=> extracting templates ...")
    tem_path = cfg.template_dir if cfg.template_dir else os.path.join(cfg.output_dir, 'templates')
    all_tem, all_tem_pts, all_tem_choose = get_templates(tem_path, cfg.test_dataset)
    with torch.inference_mode():
        all_tem_pts, all_tem_feat = model.feature_extraction.get_obj_feats(all_tem, all_tem_pts, all_tem_choose)

    print("=> loading input data ...")
    input_data, img, whole_pts, model_points, detections = get_test_data(
        cfg.rgb_path, cfg.depth_path, cfg.cam_path, cfg.cad_path, cfg.seg_path, 
        cfg.det_score_thresh, cfg.test_dataset
    )
    ninstance = input_data['pts'].size(0)
    
    print("=> running model ...")
    with torch.inference_mode():
        input_data['dense_po'] = all_tem_pts.repeat(ninstance,1,1)
        input_data['dense_fo'] = all_tem_feat.repeat(ninstance,1,1)
        out = model(input_data)

    if 'pred_pose_score' in out.keys():
        pose_scores = out['pred_pose_score'] * out['score']
    else:
        pose_scores = out['score']
    pose_scores = pose_scores.detach().cpu().numpy()
    pred_rot = out['pred_R'].detach().cpu().numpy()
    pred_trans = out['pred_t'].detach().cpu().numpy() * 1000

    print("=> saving results ...")
    os.makedirs(f"{cfg.output_dir}/sam6d_results", exist_ok=True)
    for idx, det in enumerate(detections):
        detections[idx]['score'] = float(pose_scores[idx])
        detections[idx]['R'] = list(pred_rot[idx].tolist())
        detections[idx]['t'] = list(pred_trans[idx].tolist())

    with open(os.path.join(f"{cfg.output_dir}/sam6d_results", 'detection_pem.json'), "w") as f:
        json.dump(detections, f)

    print("=> visualizating ...")
    save_path = os.path.join(f"{cfg.output_dir}/sam6d_results", 'vis_pem.png')
    valid_masks = pose_scores == pose_scores.max()
    K = input_data['K'].detach().cpu().numpy()[valid_masks]
    vis_img = visualize(img, pred_rot[valid_masks], pred_trans[valid_masks], model_points*1000, K, save_path)
    vis_img.save(save_path)
